{% set name = "types-python-gflags" %}
{% set version = "3.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-python-gflags-{{ version }}.tar.gz
  sha256: e6f1f9df262fbb9083e4b57c82ceb82836ef3ffe8229911e7ab55d916d4ab987

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/gflags-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for python-gflags
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
