{% set version = "3.1.7.20241205" %}

{% set python_min = python_min | default("3.9") %}

package:
  name: types-python-gflags
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/types-python-gflags/types_python_gflags-{{ version }}.tar.gz
  sha256: c1a19bfaa6cece4df13354d42d722cc9634d5388b6dddd46f7a6d523f63ac80e

build:
  number: 0
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
  commands:
    - pip check
    - test -f $SP_DIR/gflags-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for python-gflags
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
